# Generated by Django 6.0.1 on 2026-01-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Имя пользователя (необязательно)",
                max_length=150,
                null=True,
                unique=True,
            ),
        ),
    ]
