# Generated by Django 6.0.1 on 2026-01-21 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_telegram_id_user_telegram_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
